# -*- coding: utf-8 -*-
# vim: ft=yaml
---
docker_builder:
  name: Test ${INSTANCE}
  env:
    matrix:
      # - INSTANCE: debian-debian-10-develop-py3
      # - INSTANCE: debian-ubuntu-1804-develop-py3
      # - INSTANCE: redhat-centos-7-develop-py3
      # - INSTANCE: redhat-fedora-30-develop-py3
      # - INSTANCE: redhat-amazonlinux-2-develop-py2
      - INSTANCE: suse-arch-base-latest-develop-py2
      # - INSTANCE: debian-debian-9-2019-2-py3
      # - INSTANCE: debian-ubuntu-1804-2019-2-py3
      # - INSTANCE: redhat-centos-7-2019-2-py3
      # - INSTANCE: redhat-fedora-30-2019-2-py3
      # - INSTANCE: redhat-amazonlinux-2-2019-2-py2
      - INSTANCE: suse-arch-base-latest-2019-2-py2
      # - INSTANCE: debian-debian-9-2018-3-py2
      # - INSTANCE: debian-ubuntu-1604-2018-3-py2
      # - INSTANCE: redhat-centos-7-2018-3-py2
      # - INSTANCE: redhat-fedora-29-2018-3-py2
      # - INSTANCE: redhat-amazonlinux-2-2018-3-py2
      - INSTANCE: suse-arch-base-latest-2018-3-py2
      # - INSTANCE: debian-debian-8-2017-7-py2
      # - INSTANCE: debian-ubuntu-1604-2017-7-py2
      # - INSTANCE: redhat-centos-6-2017-7-py2
      # - INSTANCE: redhat-fedora-29-2017-7-py2
      # - INSTANCE: redhat-amazonlinux-2-2017-7-py2
      - INSTANCE: suse-arch-base-latest-2017-7-py2
  bundle_install_script: bundle install
  verify_script:
    - bin/kitchen verify ${INSTANCE}
